POST  http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkNydXppdG8iLCJpZCI6IjYxYWZkN2E1NGQwYTMwYWFmYmJlOTFjNSIsImlhdCI6MTYzOTAwNzE5Nn0.SZHPMuQLKl8lAaHP0udTQlZwvbSyK6BJUOUkxnlMQOM

{
    "content": "Cruzito",
    "important": false
}